// aula14/src/components/Contatos.svelte
<script>
    import FormContato from './FormContato.svelte';

    let contatos = [];

    $: numContatos = contatos.length;

    const salvarContato = (event) => {
        contatos = [
            ...contatos,
            {
                nome: event.detail.nome,
                telefone: event.detail.telefone,
            },
        ];
    };

    const excluirContato = (idx) => {
        let copy = [...contatos];
        copy.splice(idx, 1);
        contatos = copy;
    };
</script>

<main>
    <h1>Agenda Svelte</h1>

    <hr />

    <FormContato on:novo-contato={salvarContato} />

    <div class="list-group">
        {#if numContatos <= 0}
            <p>Adicione um contato na agenda...</p>
        {:else}
            <p>Há {numContatos} {numContatos === 1 ? 'contato' : 'contatos'} na agenda.</p>
        {/if}

        {#each contatos as contato, index}
            <div class="list-group-item card-contato">
                <span class="nome-class">Nome: <strong>{contato.nome}</strong></span>
                <p>
                    <span class="telefone_class">
                        Telefone: <strong>{contato.telefone}</strong>
                    </span>
                </p>
                <div>
                    <button title="Excluir" on:click={() => excluirContato(index)}>
                        Excluir
                    </button>
                </div>
            </div>
        {/each}
    </div>

    <hr />
</main>

<style>
    .nome-class {
        margin-top: 3px;
    }

    .card-contato {
        margin-top: 5px;
    }
</style>

// aula13/vue-parcel/components/Contatos.vue
<template>
  <div class="container">
    <h1>Agenda</h1>

    <hr />

    <FormContato v-on:add-contato="salvarContato"></FormContato>

    <div class="list-group">
      <p v-if="numContatos <= 0">Adicione um contato na agenda...</p>
      <p v-else>Há {{ numContatos }} contatos na agenda.</p>

      <div class="list-group-item" v-for="(contato, index) in contatos" v-bind:key="index">
        <span class="nome_class"
          >Nome: <strong>{{ contato.nome }}</strong></span
        >
        <p>
          <span class="telefone_class">
            Telefone: <strong>{{ contato.telefone }}</strong>
          </span>
        </p>
        <div>
          <a href="#" title="Excluir" v-on:click.prevent="excluirContato(index)"> Excluir </a>
        </div>
      </div>
    </div>

    <hr />
  </div>
</template>

<script>
import FormContato from './FormContato';

export default {
  components: {
    FormContato,
  },
  data() {
    return {
      contatos: [],
    };
  },
  methods: {
    salvarContato(contato) {
      this.contatos.push(contato);
    },
    excluirContato(index) {
      this.contatos.splice(index, 1);
    },
  },
  computed: {
    numContatos() {
      return this.contatos.length;
    },
  },
  watch: {
    contatos(val) {
      console.log('val', val);
    },
  },
};
</script>
